services:
    logrotate:
        image: ghcr.io/vdx-vn/logrotate
        environment:
            - CRON_SCHEDULE=0 * * * * # Cron schedule for logrotate
        volumes:
            - ./logs:/var/log/logrotate # logs folder
            - ./.:/conf # config folder
        restart: always
