name: Dispatch workflow on Executor repository
on:
    push:

env:
    repo_owner: ${{github.repository_owner}}
    repo_name: ${{github.repository}}
    gh_token: ${{ secrets.GH_TOKEN }}

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Login to GitHub container registry
              run: |
                  export DOCKER_PASSWORD=${{env.gh_token}}
                  docker login ghcr.io -u ${{env.repo_owner}} --password-stdin

            - name: Build image
              run: |
                  cd ${{ github.workspace }}
                  docker build . \
                        --tag ghcr.io/${{env.repo_name}} \
                        --label "org.opencontainers.image.source=https://github.com/${{env.repo_name}}" \
                        --label "github.run.id=${GITHUB_RUN_ID}"

            - name: Publish image to GitHub container registry
              run: |
                  docker push ghcr.io/${{env.repo_name}}

            - uses: actions/checkout@v4

            - name: Remove untagged (old) image from GitHub container registry
              uses: ./.github/actions/delete-untagged-packages
              with:
                  github_token: ${{env.gh_token}}
                  repo_name: ${{ inputs.repo_name }}
